# Generated by Django 4.1 on 2022-08-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyplant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(default='', max_length=100),
        ),
    ]
