# Generated by Django 4.1 on 2022-08-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyplant', '0002_alter_company_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esginitiatives',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
    ]
