# Generated by Django 4.1 on 2022-08-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyplant', '0003_alter_esginitiatives_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bloomberg_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='market_cap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='recommendation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='target_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='industry',
            name='esgScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
